linters:
  enable:
  - errcheck
  - gci
  - goconst
  - gofmt
  - gosec
  - govet
  - ineffassign
  - lll
  - megacheck
  - misspell
  - nakedret
  - revive
  - unconvert
  - unused
  enable-all: false
run:
  skip-files:
  - schema.go
  - pulumiManifest.go
  timeout: 20m
linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard library packages.
      - blank # Blank section: contains all blank imports.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/pulumi/) # Custom section: groups all imports with the github.com/pulumi/ prefix.
      - prefix(github.com/komminarlabs/pulumi-influxdb) # Custom section: local imports
    custom-order: true
