archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-influxdb
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -s
      - -w
      - -X github.com/komminarlabs/pulumi-influxdb/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-influxdb/
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
