// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB
{
    public static class GetBuckets
    {
        /// <summary>
        /// Lists buckets. InfluxDB retrieves buckets owned by the organization associated with the authorization (API token).
        /// </summary>
        public static Task<GetBucketsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBucketsResult>("influxdb:index/getBuckets:getBuckets", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Lists buckets. InfluxDB retrieves buckets owned by the organization associated with the authorization (API token).
        /// </summary>
        public static Output<GetBucketsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBucketsResult>("influxdb:index/getBuckets:getBuckets", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetBucketsResult
    {
        public readonly ImmutableArray<Outputs.GetBucketsBucketResult> Buckets;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetBucketsResult(
            ImmutableArray<Outputs.GetBucketsBucketResult> buckets,

            string id)
        {
            Buckets = buckets;
            Id = id;
        }
    }
}
