// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB
{
    public static class GetLabels
    {
        /// <summary>
        /// List all labels.
        /// </summary>
        public static Task<GetLabelsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLabelsResult>("influxdb:index/getLabels:getLabels", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// List all labels.
        /// </summary>
        public static Output<GetLabelsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLabelsResult>("influxdb:index/getLabels:getLabels", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// List all labels.
        /// </summary>
        public static Output<GetLabelsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetLabelsResult>("influxdb:index/getLabels:getLabels", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetLabelsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetLabelsLabelResult> Labels;

        [OutputConstructor]
        private GetLabelsResult(
            string id,

            ImmutableArray<Outputs.GetLabelsLabelResult> labels)
        {
            Id = id;
            Labels = labels;
        }
    }
}
