// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB
{
    public static class GetTasks
    {
        /// <summary>
        /// List all tasks.
        /// </summary>
        public static Task<GetTasksResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTasksResult>("influxdb:index/getTasks:getTasks", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// List all tasks.
        /// </summary>
        public static Output<GetTasksResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTasksResult>("influxdb:index/getTasks:getTasks", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// List all tasks.
        /// </summary>
        public static Output<GetTasksResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTasksResult>("influxdb:index/getTasks:getTasks", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTasksResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetTasksTaskResult> Tasks;

        [OutputConstructor]
        private GetTasksResult(
            string id,

            ImmutableArray<Outputs.GetTasksTaskResult> tasks)
        {
            Id = id;
            Tasks = tasks;
        }
    }
}
