// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB
{
    public static class GetUser
    {
        /// <summary>
        /// Retrieves a user.
        /// </summary>
        public static Task<GetUserResult> InvokeAsync(GetUserArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUserResult>("influxdb:index/getUser:getUser", args ?? new GetUserArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a user.
        /// </summary>
        public static Output<GetUserResult> Invoke(GetUserInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserResult>("influxdb:index/getUser:getUser", args ?? new GetUserInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a user.
        /// </summary>
        public static Output<GetUserResult> Invoke(GetUserInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserResult>("influxdb:index/getUser:getUser", args ?? new GetUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUserArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The user ID.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetUserArgs()
        {
        }
        public static new GetUserArgs Empty => new GetUserArgs();
    }

    public sealed class GetUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The user ID.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetUserInvokeArgs()
        {
        }
        public static new GetUserInvokeArgs Empty => new GetUserInvokeArgs();
    }


    [OutputType]
    public sealed class GetUserResult
    {
        /// <summary>
        /// The user ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The user name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The organization ID that the user belongs to. Null if the user is not a member of any organization.
        /// </summary>
        public readonly string OrgId;
        /// <summary>
        /// The role of the user in the organization (`member` or `owner`). Null if the user is not a member of any organization.
        /// </summary>
        public readonly string OrgRole;
        /// <summary>
        /// The password of the user. This will be always `null`.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The status of a user.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetUserResult(
            string id,

            string name,

            string orgId,

            string orgRole,

            string password,

            string status)
        {
            Id = id;
            Name = name;
            OrgId = orgId;
            OrgRole = orgRole;
            Password = password;
            Status = status;
        }
    }
}
