// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package influxdb

import (
	"context"
	"reflect"

	"errors"
	"github.com/komminarlabs/pulumi-influxdb/sdk/go/influxdb/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates and manages an authorization and returns the authorization with the generated API token. Use this resource to create/manage an authorization, which generates an API token with permissions to read or write to a specific resource or type of resource.
type Authorization struct {
	pulumi.CustomResourceState

	// Authorization creation date.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// A description of the token.
	Description pulumi.StringOutput `pulumi:"description"`
	// Organization name. Specifies the organization that owns the authorization.
	Org pulumi.StringOutput `pulumi:"org"`
	// An organization ID. Specifies the organization that owns the authorization.
	OrgId pulumi.StringOutput `pulumi:"orgId"`
	// A list of permissions for an authorization.
	Permissions AuthorizationPermissionArrayOutput `pulumi:"permissions"`
	// Status of the token. Valid values are `active` or `inactive`.
	Status pulumi.StringOutput `pulumi:"status"`
	// The API token.
	Token pulumi.StringOutput `pulumi:"token"`
	// Last Authorization update date.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// A user name. Specifies the user that the authorization is scoped to.
	User pulumi.StringPtrOutput `pulumi:"user"`
	// A user ID. Specifies the user that the authorization is scoped to.
	UserId pulumi.StringPtrOutput `pulumi:"userId"`
}

// NewAuthorization registers a new resource with the given unique name, arguments, and options.
func NewAuthorization(ctx *pulumi.Context,
	name string, args *AuthorizationArgs, opts ...pulumi.ResourceOption) (*Authorization, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrgId == nil {
		return nil, errors.New("invalid value for required argument 'OrgId'")
	}
	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Authorization
	err := ctx.RegisterResource("influxdb:index/authorization:Authorization", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthorization gets an existing Authorization resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthorization(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthorizationState, opts ...pulumi.ResourceOption) (*Authorization, error) {
	var resource Authorization
	err := ctx.ReadResource("influxdb:index/authorization:Authorization", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Authorization resources.
type authorizationState struct {
	// Authorization creation date.
	CreatedAt *string `pulumi:"createdAt"`
	// A description of the token.
	Description *string `pulumi:"description"`
	// Organization name. Specifies the organization that owns the authorization.
	Org *string `pulumi:"org"`
	// An organization ID. Specifies the organization that owns the authorization.
	OrgId *string `pulumi:"orgId"`
	// A list of permissions for an authorization.
	Permissions []AuthorizationPermission `pulumi:"permissions"`
	// Status of the token. Valid values are `active` or `inactive`.
	Status *string `pulumi:"status"`
	// The API token.
	Token *string `pulumi:"token"`
	// Last Authorization update date.
	UpdatedAt *string `pulumi:"updatedAt"`
	// A user name. Specifies the user that the authorization is scoped to.
	User *string `pulumi:"user"`
	// A user ID. Specifies the user that the authorization is scoped to.
	UserId *string `pulumi:"userId"`
}

type AuthorizationState struct {
	// Authorization creation date.
	CreatedAt pulumi.StringPtrInput
	// A description of the token.
	Description pulumi.StringPtrInput
	// Organization name. Specifies the organization that owns the authorization.
	Org pulumi.StringPtrInput
	// An organization ID. Specifies the organization that owns the authorization.
	OrgId pulumi.StringPtrInput
	// A list of permissions for an authorization.
	Permissions AuthorizationPermissionArrayInput
	// Status of the token. Valid values are `active` or `inactive`.
	Status pulumi.StringPtrInput
	// The API token.
	Token pulumi.StringPtrInput
	// Last Authorization update date.
	UpdatedAt pulumi.StringPtrInput
	// A user name. Specifies the user that the authorization is scoped to.
	User pulumi.StringPtrInput
	// A user ID. Specifies the user that the authorization is scoped to.
	UserId pulumi.StringPtrInput
}

func (AuthorizationState) ElementType() reflect.Type {
	return reflect.TypeOf((*authorizationState)(nil)).Elem()
}

type authorizationArgs struct {
	// A description of the token.
	Description *string `pulumi:"description"`
	// An organization ID. Specifies the organization that owns the authorization.
	OrgId string `pulumi:"orgId"`
	// A list of permissions for an authorization.
	Permissions []AuthorizationPermission `pulumi:"permissions"`
	// Status of the token. Valid values are `active` or `inactive`.
	Status *string `pulumi:"status"`
	// A user name. Specifies the user that the authorization is scoped to.
	User *string `pulumi:"user"`
	// A user ID. Specifies the user that the authorization is scoped to.
	UserId *string `pulumi:"userId"`
}

// The set of arguments for constructing a Authorization resource.
type AuthorizationArgs struct {
	// A description of the token.
	Description pulumi.StringPtrInput
	// An organization ID. Specifies the organization that owns the authorization.
	OrgId pulumi.StringInput
	// A list of permissions for an authorization.
	Permissions AuthorizationPermissionArrayInput
	// Status of the token. Valid values are `active` or `inactive`.
	Status pulumi.StringPtrInput
	// A user name. Specifies the user that the authorization is scoped to.
	User pulumi.StringPtrInput
	// A user ID. Specifies the user that the authorization is scoped to.
	UserId pulumi.StringPtrInput
}

func (AuthorizationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authorizationArgs)(nil)).Elem()
}

type AuthorizationInput interface {
	pulumi.Input

	ToAuthorizationOutput() AuthorizationOutput
	ToAuthorizationOutputWithContext(ctx context.Context) AuthorizationOutput
}

func (*Authorization) ElementType() reflect.Type {
	return reflect.TypeOf((**Authorization)(nil)).Elem()
}

func (i *Authorization) ToAuthorizationOutput() AuthorizationOutput {
	return i.ToAuthorizationOutputWithContext(context.Background())
}

func (i *Authorization) ToAuthorizationOutputWithContext(ctx context.Context) AuthorizationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationOutput)
}

// AuthorizationArrayInput is an input type that accepts AuthorizationArray and AuthorizationArrayOutput values.
// You can construct a concrete instance of `AuthorizationArrayInput` via:
//
//	AuthorizationArray{ AuthorizationArgs{...} }
type AuthorizationArrayInput interface {
	pulumi.Input

	ToAuthorizationArrayOutput() AuthorizationArrayOutput
	ToAuthorizationArrayOutputWithContext(context.Context) AuthorizationArrayOutput
}

type AuthorizationArray []AuthorizationInput

func (AuthorizationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Authorization)(nil)).Elem()
}

func (i AuthorizationArray) ToAuthorizationArrayOutput() AuthorizationArrayOutput {
	return i.ToAuthorizationArrayOutputWithContext(context.Background())
}

func (i AuthorizationArray) ToAuthorizationArrayOutputWithContext(ctx context.Context) AuthorizationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationArrayOutput)
}

// AuthorizationMapInput is an input type that accepts AuthorizationMap and AuthorizationMapOutput values.
// You can construct a concrete instance of `AuthorizationMapInput` via:
//
//	AuthorizationMap{ "key": AuthorizationArgs{...} }
type AuthorizationMapInput interface {
	pulumi.Input

	ToAuthorizationMapOutput() AuthorizationMapOutput
	ToAuthorizationMapOutputWithContext(context.Context) AuthorizationMapOutput
}

type AuthorizationMap map[string]AuthorizationInput

func (AuthorizationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Authorization)(nil)).Elem()
}

func (i AuthorizationMap) ToAuthorizationMapOutput() AuthorizationMapOutput {
	return i.ToAuthorizationMapOutputWithContext(context.Background())
}

func (i AuthorizationMap) ToAuthorizationMapOutputWithContext(ctx context.Context) AuthorizationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthorizationMapOutput)
}

type AuthorizationOutput struct{ *pulumi.OutputState }

func (AuthorizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Authorization)(nil)).Elem()
}

func (o AuthorizationOutput) ToAuthorizationOutput() AuthorizationOutput {
	return o
}

func (o AuthorizationOutput) ToAuthorizationOutputWithContext(ctx context.Context) AuthorizationOutput {
	return o
}

// Authorization creation date.
func (o AuthorizationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// A description of the token.
func (o AuthorizationOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Organization name. Specifies the organization that owns the authorization.
func (o AuthorizationOutput) Org() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.Org }).(pulumi.StringOutput)
}

// An organization ID. Specifies the organization that owns the authorization.
func (o AuthorizationOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.OrgId }).(pulumi.StringOutput)
}

// A list of permissions for an authorization.
func (o AuthorizationOutput) Permissions() AuthorizationPermissionArrayOutput {
	return o.ApplyT(func(v *Authorization) AuthorizationPermissionArrayOutput { return v.Permissions }).(AuthorizationPermissionArrayOutput)
}

// Status of the token. Valid values are `active` or `inactive`.
func (o AuthorizationOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The API token.
func (o AuthorizationOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Last Authorization update date.
func (o AuthorizationOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// A user name. Specifies the user that the authorization is scoped to.
func (o AuthorizationOutput) User() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringPtrOutput { return v.User }).(pulumi.StringPtrOutput)
}

// A user ID. Specifies the user that the authorization is scoped to.
func (o AuthorizationOutput) UserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Authorization) pulumi.StringPtrOutput { return v.UserId }).(pulumi.StringPtrOutput)
}

type AuthorizationArrayOutput struct{ *pulumi.OutputState }

func (AuthorizationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Authorization)(nil)).Elem()
}

func (o AuthorizationArrayOutput) ToAuthorizationArrayOutput() AuthorizationArrayOutput {
	return o
}

func (o AuthorizationArrayOutput) ToAuthorizationArrayOutputWithContext(ctx context.Context) AuthorizationArrayOutput {
	return o
}

func (o AuthorizationArrayOutput) Index(i pulumi.IntInput) AuthorizationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Authorization {
		return vs[0].([]*Authorization)[vs[1].(int)]
	}).(AuthorizationOutput)
}

type AuthorizationMapOutput struct{ *pulumi.OutputState }

func (AuthorizationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Authorization)(nil)).Elem()
}

func (o AuthorizationMapOutput) ToAuthorizationMapOutput() AuthorizationMapOutput {
	return o
}

func (o AuthorizationMapOutput) ToAuthorizationMapOutputWithContext(ctx context.Context) AuthorizationMapOutput {
	return o
}

func (o AuthorizationMapOutput) MapIndex(k pulumi.StringInput) AuthorizationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Authorization {
		return vs[0].(map[string]*Authorization)[vs[1].(string)]
	}).(AuthorizationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationInput)(nil)).Elem(), &Authorization{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationArrayInput)(nil)).Elem(), AuthorizationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthorizationMapInput)(nil)).Elem(), AuthorizationMap{})
	pulumi.RegisterOutputType(AuthorizationOutput{})
	pulumi.RegisterOutputType(AuthorizationArrayOutput{})
	pulumi.RegisterOutputType(AuthorizationMapOutput{})
}
