// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package influxdb

import (
	"context"
	"reflect"

	"github.com/komminarlabs/pulumi-influxdb/sdk/go/influxdb/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// List all tasks.
func GetTasks(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetTasksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTasksResult
	err := ctx.Invoke("influxdb:index/getTasks:getTasks", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getTasks.
type GetTasksResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id    string         `pulumi:"id"`
	Tasks []GetTasksTask `pulumi:"tasks"`
}

func GetTasksOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetTasksResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetTasksResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("influxdb:index/getTasks:getTasks", nil, GetTasksResultOutput{}, options).(GetTasksResultOutput), nil
	}).(GetTasksResultOutput)
}

// A collection of values returned by getTasks.
type GetTasksResultOutput struct{ *pulumi.OutputState }

func (GetTasksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTasksResult)(nil)).Elem()
}

func (o GetTasksResultOutput) ToGetTasksResultOutput() GetTasksResultOutput {
	return o
}

func (o GetTasksResultOutput) ToGetTasksResultOutputWithContext(ctx context.Context) GetTasksResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetTasksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTasksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTasksResultOutput) Tasks() GetTasksTaskArrayOutput {
	return o.ApplyT(func(v GetTasksResult) []GetTasksTask { return v.Tasks }).(GetTasksTaskArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTasksResultOutput{})
}
