name: "Report a Bug"
description: "Create a bug report to help us improve."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Hi there,
        Thank you for opening an issue! Please note that we try to keep the this issue tracker reserved for
        bug reports and feature requests related to the InfluxDB provider.

  - type: markdown
    attributes:
      value: |
        # Pulumi and InfluxDB Provider Versions

  - type: input
    id: pulumi_version
    attributes:
      label: Pulumi Version
      description: The semantic version of Pulumi used when experiencing the bug. If multiple versions have been tested, a comma separated list.
      placeholder: "X.Y.Z"
    validations:
      required: true

  - type: input
    id: influxdb_version
    attributes:
      label: InfluxDB Provider Version
      description: The semantic version of the InfluxDB Provider used when experiencing the bug. If multiple versions have been tested, a comma separated list.
      placeholder: "X.Y.Z"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Description

        In the next few fields, please provide any useful information you can around what resources are affected, what you expected to happen, and what actually happened. There is also a field to optionally provide a small snippet of any relevant error or panic output.

        Note that there is a section later in the form to provide more complete Pulumi configuration and logging information. These fields should instead be thought of as the place to briefly describe the bug.

  - type: textarea
    id: affected
    attributes:
      label: Affected Resource(s)
      description: Please list the affected resource(s) and/or function(s).
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: log_snippet
    attributes:
      label: Relevant Error/Panic Output Snippet
      description: |
        If applicable, provide a relevant snippet from the error or panic output. This will be rendered as `shell`, so there is no need to add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Configuration and Logging

        Here, we ask that you provide the Pulumi configuration and, when possible, the debug logs. For configurations or logs of more than just a few lines, it's preferred to either share a Gist link or zip the files and upload them.

        Pulumi configurations or debug logs under 25MB may be [attached directly in the field](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files). Files larger than this should be uploaded to a file hosting service and a link shared.

        For your security you can also encrypt the files using our [GPG public key](https://keybase.io/hashicorp).

        **Note:** These form fields do not automatically render, so you will need to use [code fence(s)](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) to achieve proper formatting.

  - type: textarea
    id: tf_config
    attributes:
      label: Pulumi Configuration Files
      description: |
        Please paste, upload, or link to a file or Gist containing all Pulumi configurations required to reproduce the bug. See note above for additional information on file size restrictions and encrypting.

        Bug reports without a functional reproduction may be closed without investigation.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Please list the steps required to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: debug_logs
    attributes:
      label: Debug Output
      description: |
        If possible, please paste, upload, or link to a file or Gist containing debug logs. See note above for additional information on file size restrictions and encrypting.

    validations:
      required: false

  - type: textarea
    id: panic_logs
    attributes:
      label: Panic Output
      description: If Pulumi produced a panic, please paste, upload, or link to a file or Gist containing the output of the `crash.log`.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Additional Information

        For the final two fields, optionally provide any additional context that might help the community or maintainers to investigate the bug. This might be additional references that you found when troubleshooting, similar bug reports, or specifics about your environment that might be unique.

  - type: textarea
    attributes:
      label: Important Factoids
      description: Are there anything atypical about your configuration or environment that we should know about?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false
