// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class AuthorizationPermission
    {
        /// <summary>
        /// Permission action. Valid values are `read` or `write`.
        /// </summary>
        public readonly string Action;
        public readonly Outputs.AuthorizationPermissionResource Resource;

        [OutputConstructor]
        private AuthorizationPermission(
            string action,

            Outputs.AuthorizationPermissionResource resource)
        {
            Action = action;
            Resource = resource;
        }
    }
}
