// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class GetAuthorizationsAuthorizationPermissionResourceResult
    {
        /// <summary>
        /// The authorization ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the resource. Note: not all resource types have a name property.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// An Organization name. Specifies the organization that owns the authorization.
        /// </summary>
        public readonly string Org;
        /// <summary>
        /// An organization ID. Specifies the organization that owns the authorization.
        /// </summary>
        public readonly string OrgId;
        /// <summary>
        /// A resource type. Identifies the API resource's type (or kind).
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetAuthorizationsAuthorizationPermissionResourceResult(
            string id,

            string name,

            string org,

            string orgId,

            string type)
        {
            Id = id;
            Name = name;
            Org = org;
            OrgId = orgId;
            Type = type;
        }
    }
}
