// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class GetAuthorizationsAuthorizationPermissionResult
    {
        /// <summary>
        /// Permission action.
        /// </summary>
        public readonly string Action;
        public readonly Outputs.GetAuthorizationsAuthorizationPermissionResourceResult Resource;

        [OutputConstructor]
        private GetAuthorizationsAuthorizationPermissionResult(
            string action,

            Outputs.GetAuthorizationsAuthorizationPermissionResourceResult resource)
        {
            Action = action;
            Resource = resource;
        }
    }
}
