// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class GetLabelsLabelResult
    {
        /// <summary>
        /// The label ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The label name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The organization ID.
        /// </summary>
        public readonly string OrgId;
        /// <summary>
        /// The key-value pairs associated with this label.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Properties;

        [OutputConstructor]
        private GetLabelsLabelResult(
            string id,

            string name,

            string orgId,

            ImmutableDictionary<string, string> properties)
        {
            Id = id;
            Name = name;
            OrgId = orgId;
            Properties = properties;
        }
    }
}
