// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class GetTaskLinksResult
    {
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Labels;
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Logs;
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Members;
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Owners;
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Runs;
        /// <summary>
        /// URI of resource.
        /// </summary>
        public readonly string Self;

        [OutputConstructor]
        private GetTaskLinksResult(
            string labels,

            string logs,

            string members,

            string owners,

            string runs,

            string self)
        {
            Labels = labels;
            Logs = logs;
            Members = members;
            Owners = owners;
            Runs = runs;
            Self = self;
        }
    }
}
