// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Outputs
{

    [OutputType]
    public sealed class GetUsersUserResult
    {
        /// <summary>
        /// The user ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The user name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The organization ID that the user belongs to. Null if the user is not a member of any organization.
        /// </summary>
        public readonly string OrgId;
        /// <summary>
        /// The role of the user in the organization (`member` or `owner`). Null if the user is not a member of any organization.
        /// </summary>
        public readonly string OrgRole;
        /// <summary>
        /// The password of the user. This will be always `null`.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The status of a user.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetUsersUserResult(
            string id,

            string name,

            string orgId,

            string orgRole,

            string password,

            string status)
        {
            Id = id;
            Name = name;
            OrgId = orgId;
            OrgRole = orgRole;
            Password = password;
            Status = status;
        }
    }
}
