// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/komminarlabs/pulumi-influxdb/sdk/go/influxdb/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The InfluxDB password
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb:password")
}

// An InfluxDB token string
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb:token")
}

// The InfluxDB Cloud Dedicated server URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb:url")
}

// The InfluxDB username
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb:username")
}
