// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AuthorizationPermission {
    /**
     * Permission action. Valid values are `read` or `write`.
     */
    action: pulumi.Input<string>;
    resource: pulumi.Input<inputs.AuthorizationPermissionResource>;
}

export interface AuthorizationPermissionResource {
    /**
     * A resource ID. Identifies a specific resource.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the resource. **Note:** not all resource types have a name property.
     */
    name?: pulumi.Input<string>;
    /**
     * An organization name. The organization that owns the resource.
     */
    org?: pulumi.Input<string>;
    /**
     * An organization ID. Identifies the organization that owns the resource.
     */
    orgId?: pulumi.Input<string>;
    /**
     * A resource type. Identifies the API resource's type (or kind).
     */
    type: pulumi.Input<string>;
}

export interface TaskLabel {
    /**
     * The label ID.
     */
    id?: pulumi.Input<string>;
    /**
     * The label name.
     */
    name?: pulumi.Input<string>;
    /**
     * The organization ID.
     */
    orgId?: pulumi.Input<string>;
    /**
     * The key-value pairs associated with this label.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

export interface TaskLinks {
    /**
     * URI of resource.
     */
    labels?: pulumi.Input<string>;
    /**
     * URI of resource.
     */
    logs?: pulumi.Input<string>;
    /**
     * URI of resource.
     */
    members?: pulumi.Input<string>;
    /**
     * URI of resource.
     */
    owners?: pulumi.Input<string>;
    /**
     * URI of resource.
     */
    runs?: pulumi.Input<string>;
    /**
     * URI of resource.
     */
    self?: pulumi.Input<string>;
}
