// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AuthorizationPermission {
    /**
     * Permission action. Valid values are `read` or `write`.
     */
    action: pulumi.Input<string>;
    resource: pulumi.Input<inputs.AuthorizationPermissionResource>;
}

export interface AuthorizationPermissionResource {
    /**
     * A resource ID. Identifies a specific resource.
     */
    id: pulumi.Input<string>;
    /**
     * The name of the resource. **Note:** not all resource types have a name property.
     */
    name?: pulumi.Input<string>;
    /**
     * An organization name. The organization that owns the resource.
     */
    org?: pulumi.Input<string>;
    /**
     * An organization ID. Identifies the organization that owns the resource.
     */
    orgId: pulumi.Input<string>;
    /**
     * A resource type. Identifies the API resource's type (or kind).
     */
    type: pulumi.Input<string>;
}

