// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Inputs
{

    public sealed class AuthorizationPermissionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Permission action. Valid values are `read` or `write`.
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        [Input("resource", required: true)]
        public Input<Inputs.AuthorizationPermissionResourceGetArgs> Resource { get; set; } = null!;

        public AuthorizationPermissionGetArgs()
        {
        }
        public static new AuthorizationPermissionGetArgs Empty => new AuthorizationPermissionGetArgs();
    }
}
