// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB.Inputs
{

    public sealed class TaskLinksGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("labels")]
        public Input<string>? Labels { get; set; }

        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("logs")]
        public Input<string>? Logs { get; set; }

        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("members")]
        public Input<string>? Members { get; set; }

        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("owners")]
        public Input<string>? Owners { get; set; }

        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("runs")]
        public Input<string>? Runs { get; set; }

        /// <summary>
        /// URI of resource.
        /// </summary>
        [Input("self")]
        public Input<string>? Self { get; set; }

        public TaskLinksGetArgs()
        {
        }
        public static new TaskLinksGetArgs Empty => new TaskLinksGetArgs();
    }
}
