name: CI

on:
    pull_request:
      branches:
        - main
      paths-ignore:
        - docs/**
        - examples/**
        - .github/**

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - uses: actions/setup-go@v5
        with:
            go-version: 'stable'
      
      - name: Gather dependencies
        run: go mod download

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            token: ${{ secrets.CODECOV_ORG_TOKEN }}