name: PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - .devcontainer/**
      - examples/**
      - .github/**

jobs:
  license_check:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - run: ls -all

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            sdk/go.sum
          go-version: 1.22.x

      - run: make upstream

      - name: License Check
        uses: pulumi/license-check-action@main
        with:
          module-path: provider
          ignore-modules: >-
            github.com/aead/chacha20,
            github.com/apache/arrow/go/v12,
            github.com/apache/thrift/lib/go/thrift,
            github.com/cloudflare/circl,
            github.com/golang,
            github.com/gorhill/cronexpr,
            github.com/in-toto/in-toto-golang,
            github.com/jmespath/go-jmespath,
            github.com/keybase/go-crypto,
            github.com/klauspost/compress,
            github.com/mattn/go-localereader,
            github.com/modern-go/reflect2,
            github.com/pierrec/lz4,
            github.com/pjbgf/sha1cd,
            github.com/pulumi,
            github.com/segmentio/asm,
            golang.org,
            github.com/komminarlabs/terraform-provider-influxdb/shim
