name: PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - .devcontainer/**
      - .github/**

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false

      - name: Disarm go:embed directives to enable lint
        continue-on-error: true
        run: |
          git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'

      - name: Prepare Upstream
        continue-on-error: true
        run: make upstream

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          working-directory: provider
