// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Lists all authorizations.
 */
export function getAuthorizations(opts?: pulumi.InvokeOptions): Promise<GetAuthorizationsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getAuthorizations:getAuthorizations", {
    }, opts);
}

/**
 * A collection of values returned by getAuthorizations.
 */
export interface GetAuthorizationsResult {
    readonly authorizations: outputs.GetAuthorizationsAuthorization[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * Lists all authorizations.
 */
export function getAuthorizationsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetAuthorizationsResult> {
    return pulumi.output(getAuthorizations(opts))
}
