// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Lists buckets. InfluxDB retrieves buckets owned by the organization associated with the authorization (API token).
 */
export function getBuckets(opts?: pulumi.InvokeOptions): Promise<GetBucketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getBuckets:getBuckets", {
    }, opts);
}

/**
 * A collection of values returned by getBuckets.
 */
export interface GetBucketsResult {
    readonly buckets: outputs.GetBucketsBucket[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * Lists buckets. InfluxDB retrieves buckets owned by the organization associated with the authorization (API token).
 */
export function getBucketsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBucketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("influxdb:index/getBuckets:getBuckets", {
    }, opts);
}
