// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * List all labels.
 */
export function getLabels(opts?: pulumi.InvokeOptions): Promise<GetLabelsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getLabels:getLabels", {
    }, opts);
}

/**
 * A collection of values returned by getLabels.
 */
export interface GetLabelsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: outputs.GetLabelsLabel[];
}
/**
 * List all labels.
 */
export function getLabelsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLabelsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("influxdb:index/getLabels:getLabels", {
    }, opts);
}
