// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * List all tasks.
 */
export function getTasks(opts?: pulumi.InvokeOptions): Promise<GetTasksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getTasks:getTasks", {
    }, opts);
}

/**
 * A collection of values returned by getTasks.
 */
export interface GetTasksResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly tasks: outputs.GetTasksTask[];
}
/**
 * List all tasks.
 */
export function getTasksOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTasksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("influxdb:index/getTasks:getTasks", {
    }, opts);
}
