// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates and manages a user with optional organization membership. Supports adding users as members or owners of organizations.
 *
 * **Note:** InfluxDB Cloud doesn't let you manage user passwords through the API. Use the InfluxDB Cloud user interface (UI) to update your password.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'influxdb:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The user name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The organization ID to add the user to. Required when `orgRole` is specified.
     */
    public readonly orgId!: pulumi.Output<string | undefined>;
    /**
     * The role of the user in the organization (`member` or `owner`).
     */
    public readonly orgRole!: pulumi.Output<string | undefined>;
    /**
     * The password to set for the user.
     */
    public readonly password!: pulumi.Output<string>;
    /**
     * The status of a user. Default: `active`
     */
    public readonly status!: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["orgId"] = state ? state.orgId : undefined;
            resourceInputs["orgRole"] = state ? state.orgRole : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if ((!args || args.password === undefined) && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["orgId"] = args ? args.orgId : undefined;
            resourceInputs["orgRole"] = args ? args.orgRole : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The user name.
     */
    name?: pulumi.Input<string>;
    /**
     * The organization ID to add the user to. Required when `orgRole` is specified.
     */
    orgId?: pulumi.Input<string>;
    /**
     * The role of the user in the organization (`member` or `owner`).
     */
    orgRole?: pulumi.Input<string>;
    /**
     * The password to set for the user.
     */
    password?: pulumi.Input<string>;
    /**
     * The status of a user. Default: `active`
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The user name.
     */
    name?: pulumi.Input<string>;
    /**
     * The organization ID to add the user to. Required when `orgRole` is specified.
     */
    orgId?: pulumi.Input<string>;
    /**
     * The role of the user in the organization (`member` or `owner`).
     */
    orgRole?: pulumi.Input<string>;
    /**
     * The password to set for the user.
     */
    password: pulumi.Input<string>;
    /**
     * The status of a user. Default: `active`
     */
    status?: pulumi.Input<string>;
}
